# Generated by Django 5.2.2 on 2025-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
